factionInfo = {
	"Arborec" 	: {
		"maxComm" 		: 3,
		"technology" 	: ["Magen Defense Grid Omega"],
		"planets"		: {"Nestphar" : {"exhausted" : False, "resources" : 3, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Stymie Omega"],
		"leaders"		: {"agent" : [{"name" : "Letani Odpha", "exhausted" : False}], 
						"commander" : [{"name" : "Dirzuga Rophal", "unlocked" : False}], 
						"hero" : [{"locked name" : "Letani Miasmiala", "unlocked name" : "Ultrasonic Emitter", "unlocked" : False}]}
	}, 
	"Argent" 	: {
		"maxComm" 		: 3,
		"technology" 	: ["Choose 2: Neural Motivator, Sarween Tools, Plasma Scoring"],
		"planets"		: {"Ylir" : {"exhausted" : False, "resources" : 0, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Valk" : {"exhausted" : False, "resources" : 2, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Avar" : {"exhausted" : False, "resources" : 1, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Strike Wing Ambuscade"],
		"leaders"		: {"agent" : [{"name" : "Trilossa Aun Mirik", "exhausted" : False}], 
						"commander" : [{"name" : "Trrakan Aun Zulok", "unlocked" : False}], 
						"hero" : [{"locked name" : "Mirik Aun Sissiri", "unlocked name" : "Helix Protocol", "unlocked" : False}]}
	}, 
	"Barony" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Antimass Deflectors", "Plasma Scoring"],
		"planets"		: {"Arc Prime" : {"exhausted" : False, "resources" : 4, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Wren Terra" : {"exhausted" : False, "resources" : 2, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["War Funding Omega"],
		"leaders"		: {"agent" : [{"name" : "Viscount Unlenn", "exhausted" : False}], 
						"commander" : [{"name" : "Rear Admiral Farran", "unlocked" : False}], 
						"hero" : [{"locked name" : "Darktalon Treilla", "unlocked name" : "Dark Matter Affinity", "unlocked" : False}]}
	},
	"Cabal" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Self-Assembly Routines"],
		"planets"		: {"Acheron" : {"exhausted" : False, "resources" : 4, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Crucible"],
		"leaders"		: {"agent" : [{"name" : "The Stillness of Stars", "exhausted" : False}], 
						"commander" : [{"name" : "That Which Molds Flesh", "unlocked" : False}], 
						"hero" : [{"locked name" : "It Feeds on Carrion", "unlocked name" : "Dimensional Anchor", "unlocked" : False}]},
		"additionalcomponents" : {"Dimensional Tear Tokens" : 3}
	}, 
    "Empyrean" 	: {
		"maxComm" 		: 4,
		"technology" 	: ["Dark Energy Tap"],
		"planets"		: {"The Dark" : {"exhausted" : False, "resources" : 3, "influence" : 4, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Blood Pact", "Dark Pact"],
		"leaders"		: {"agent" : [{"name" : "Acamar", "exhausted" : False}], 
						"commander" : [{"name" : "Xuange", "unlocked" : False}], 
						"hero" : [{"locked name" : "Conservator Procyon", "unlocked name" : "Multiverse Shift", "unlocked" : False}]}
	},
    "Ghosts" 	: {
		"maxComm" 		: 4,
		"technology" 	: ["Gravity Drive"],
		"planets"		: {"Creuss" : {"exhausted" : False, "resources" : 4, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Creuss IFF"],
		"leaders"		: {"agent" : [{"name" : "Emissary Taivra", "exhausted" : False}], 
						"commander" : [{"name" : "Sai Seravus", "unlocked" : False}], 
						"hero" : [{"locked name" : "Riftwalker Meian", "unlocked name" : "Singularity Reactor", "unlocked" : False}]},
		"additionalcomponents" : {"wormhole tokens" : ["creuss alpha token", "creuss beta token", "creuss gamma token"]}
	},
    "Hacan" 	: {
		"maxComm" 		: 6,
		"technology" 	: ["Antimass Deflectors", "Sarween Tools"],
		"planets"		: {"Hercant" : {"exhausted" : False, "resources" : 1, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"},
						"Arretze" : {"exhausted" : False, "resources" : 2, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
						"Kamdorn" : {"exhausted" : False, "resources" : 0, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Trade Convoys"],
		"leaders"		: {"agent" : [{"name" : "Carth of the Golden Sands", "exhausted" : False}], 
						"commander" : [{"name" : "Gila the Silvertongue", "unlocked" : False}], 
						"hero" : [{"locked name" : "Harrugh Gefhara", "unlocked name" : "Galactic Securities Net", "unlocked" : False}]}
	},
    "Jol-Nar" 	: {
		"maxComm" 		: 4,
		"technology" 	: ["Neural Motivator", "Antimass Deflectors", "Sarween Tools", "Plasma Scoring"],
		"planets"		: {"Jol" : {"exhausted" : False, "resources" : 1, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Nar" : {"exhausted" : False, "resources" : 2, "influence" : 3, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["research Agreement"],
		"leaders"		: {"agent" : [{"name" : "Doctor Sucaban", "exhausted" : False}], 
						"commander" : [{"name" : "Ta Zern", "unlocked" : False}], 
						"hero" : [{"locked name" : "Rin, The Master's Legacy", "unlocked name" : "Genetic Memory", "unlocked" : False}]}
	}, 
    "Keleres [Argent]" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Choose 2 technologies other players start with."],
		"planets"		: {"Ylir" : {"exhausted" : False, "resources" : 0, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Valk" : {"exhausted" : False, "resources" : 2, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Avar" : {"exhausted" : False, "resources" : 1, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Keleres Rider"],
		"leaders"		: {"agent" : [{"name" : "Xander Alexin Victori III", "exhausted" : False}], 
						"commander" : [{"name" : "Suffi An", "unlocked" : False}], 
						"hero" : [{"locked name" : "Kuuasi Aun Jalatai", "unlocked name" : "Overwing Zeta", "unlocked" : False}]}
	},
    "Keleres [Mentak]" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Choose 2 technologies other players start with."],
		"planets"		: {"Moll Primus" : {"exhausted" : False, "resources" : 4, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Keleres Rider"],
		"leaders"		: {"agent" : [{"name" : "Xander Alexin Victori III", "exhausted" : False}], 
						"commander" : [{"name" : "Suffi An", "unlocked" : False}], 
						"hero" : [{"locked name" : "Harka Leeds", "unlocked name" : "Erwan's Covenant", "unlocked" : False}]}
	},
    "Keleres [Xxcha]" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Choose 2 technologies other players start with."],
		"planets"		: {"Archon Ren" : {"exhausted" : False, "resources" : 2, "influence" : 3, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Archon Tau" : {"exhausted" : False, "resources" : 1, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"},},
		"promissoryNotes" : ["Keleres Rider"],
		"leaders"		: {"agent" : [{"name" : "Xander Alexin Victori III", "exhausted" : False}], 
						"commander" : [{"name" : "Suffi An", "unlocked" : False}], 
						"hero" : [{"locked name" : "Odlynn Myrr", "unlocked name" : "Operation Archon", "unlocked" : False}]}
	},
    "L1Z1X" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Neural Motivator", "Plasma Scoring"],
		"planets"		: {"[0.0.0]" : {"exhausted" : False, "resources" : 5, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Cybernetic Enhancements Omega"],
		"leaders"		: {"agent" : [{"name" : "L48S", "exhausted" : False}], 
						"commander" : [{"name" : "2RAM", "unlocked" : False}], 
						"hero" : [{"locked name" : "The Helmsman", "unlocked name" : "Dark Space Navigation", "unlocked" : False}]}
	},
    "Mahact" 	: {
		"maxComm" 		: 3,
		"technology" 	: ["Bio-Stims", "Predictive Intelligence"],
		"planets"		: {"Ixth" : {"exhausted" : False, "resources" : 3, "influence" : 5, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Scepter of Dominion"],
		"leaders"		: {"agent" : [{"name" : "Jae Mir Kan", "exhausted" : False}], 
						"commander" : [{"name" : "Il Na Viroset", "unlocked" : False}], 
						"hero" : [{"locked name" : "Airo Shir Aur", "unlocked name" : "Benediction", "unlocked" : False}]}
	},
    "Mentak" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Sarween Tools", "Plasma Scoring"],
		"planets"		: {"Moll Primus" : {"exhausted" : False, "resources" : 4, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Promise of Protection"],
		"leaders"		: {"agent" : [{"name" : "Suffi An", "exhausted" : False}], 
						"commander" : [{"name" : "S'ula Mentarion", "unlocked" : False}], 
						"hero" : [{"locked name" : "Ipswitch, Loose Cannon", "unlocked name" : "Sleeper Cell", "unlocked" : False}]}
	},
    "Muaat" 	: {
		"maxComm" 		: 4,
		"technology" 	: ["Plasma Scoring"],
		"planets"		: {"Muaat" : {"exhausted" : False, "resources" : 4, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Fires of the Gashlai"],
		"leaders"		: {"agent" : [{"name" : "Umbat", "exhausted" : False}], 
						"commander" : [{"name" : "Magmus", "unlocked" : False}], 
						"hero" : [{"locked name" : "Adjudicator Ba'al", "unlocked name" : "Nova Seed", "unlocked" : False}]}
	},
    "Naalu" 	: {
		"maxComm" 		: 3,
		"technology" 	: ["Sarween Tools", "Neural Motivator"],
		"planets"		: {"Druaa" : {"exhausted" : False, "resources" : 3, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Maaluuk" : {"exhausted" : False, "resources" : 0, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Gift of Presience"],
		"leaders"		: {"agent" : [{"name" : "Z'eu Omega", "exhausted" : False}], 
						"commander" : [{"name" : "M'aban Omega", "unlocked" : False}], 
						"hero" : [{"locked name" : "The Oracle", "unlocked name" : "C-Radium Geometry", "unlocked" : False}]},
		"additionalcomponents" : {"0 token" : "0 token"}
	},
    "Naaz-Rokha": {
		"maxComm" 		: 3,
		"technology" 	: ["Psychoarchaeology", "AI Development Algorithm"],
		"planets"		: {"Naazir" : {"exhausted" : False, "resources" : 2, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Rokha" : {"exhausted" : False, "resources" : 1, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Black Market Forgery"],
		"leaders"		: {"agent" : [{"name" : "Garv and Gunn", "exhausted" : False}], 
						"commander" : [{"name" : "Dart and Tai", "unlocked" : False}], 
						"hero" : [{"locked name" : "Hesh and Prit", "unlocked name" : "Perfect Synthesis", "unlocked" : False}]}
	},
    "Nekro" 	: {
		"maxComm" 		: 3,
		"technology" 	: ["Dacxive Animators", "Valefar Assimilator X", "Valefar Assimilator Y"],
		"planets"		: {"Mordai II" : {"exhausted" : False, "resources" : 4, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Antivirus"],
		"leaders"		: {"agent" : [{"name" : "Nekro Malleon", "exhausted" : False}], 
						"commander" : [{"name" : "Nekro Acidos", "unlocked" : False}], 
						"hero" : [{"locked name" : "UNIT.DSGN.FLAYESH", "unlocked name" : "Polymorphic Algorithm", "unlocked" : False}]},
		"additionalcomponents" : {"Valefar X token" : "", "Valefar Y token" : "", "Dimensional Tear Tokens" : 3}
	},
    "Nomad" 	: {
		"maxComm" 		: 4,
		"technology" 	: ["Sling Relay"],
		"planets"		: {"Arcturus" : {"exhausted" : False, "resources" : 4, "influence" : 4, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["The Cavalry"],
		"leaders"		: {"agent" : [{"name" : "The Thundarian", "exhausted" : False}, {"name" : "Artuno the Betrayer", "exhausted" : False}, {"name" : "Field Marshal Mercer", "exhausted" : False}], 
						"commander" : [{"name" : "Navarch Feng", "unlocked" : False}], 
						"hero" : [{"locked name" : "Ahk-Syl Siven", "unlocked name" : "Probability Matrix", "unlocked" : False}]}
	},
    "Saar" 		: {
		"maxComm" 		: 3,
		"technology" 	: ["Antimass Deflectors"],
		"planets"		: {"Lisis II" : {"exhausted" : False, "resources" : 1, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Ragh" : {"exhausted" : False, "resources" : 2, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Ragh's Call"],
		"leaders"		: {"agent" : [{"name" : "Captain Mendosa", "exhausted" : False}], 
						"commander" : [{"name" : "Rowl Sarrig", "unlocked" : False}], 
						"hero" : [{"locked name" : "Gurno Aggero", "unlocked name" : "Armageddon Relay", "unlocked" : False}]}
	}, 
    "Sardakk"  	: {
		"maxComm" 		: 3,
		"technology" 	: [],
		"planets"		: {"Tren'lak" : {"exhausted" : False, "resources" : 1, "influence" : 0, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Quinarra" : {"exhausted" : False, "resources" : 3, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Tekklar Legion"],
		"leaders"		: {"agent" : [{"name" : "T'ro", "exhausted" : False}], 
						"commander" : [{"name" : "G'hom Sek'kus", "unlocked" : False}], 
						"hero" : [{"locked name" : "Sh'val, Harbringer", "unlocked name" : "Tekklar Conditioning", "unlocked" : False}]}
	}, 
    "Sol"  		: {
		"maxComm" 		: 4,
		"technology" 	: ["Neural Motivator", "Antimass Deflectors"],
		"planets"		: {"Jord" : {"exhausted" : False, "resources" : 4, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Military Support"],
		"leaders"		: {"agent" : [{"name" : "Evelyn DeLouis", "exhausted" : False}], 
						"commander" : [{"name" : "Claire Gibson", "unlocked" : False}], 
						"hero" : [{"locked name" : "Jace X, 4th Air Legion", "unlocked name" : "Helio Command Array", "unlocked" : False}]}
	},
    "Titans" 	: {
		"maxComm" 		: 2,
		"technology" 	: ["Antimass Deflectors", "Scanlink Drone Network"],
		"planets"		: {"Elysium" : {"exhausted" : False, "resources" : 4, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Terraform"],
		"leaders"		: {"agent" : [{"name" : "Tellurian", "exhausted" : False}], 
						"commander" : [{"name" : "Tungstantus", "unlocked" : False}], 
						"hero" : [{"locked name" : "Ul the Progenitor", "unlocked name" : "Geoform", "unlocked" : False}]},
		"additionalcomponents" : {"sleeper token" : 5}
	}, 
    "Winnu"  	: {
		"maxComm" 		: 3,
		"technology" 	: ["Choose 1 technology with no prerequisites."],
		"planets"		: {"Winnu" : {"exhausted" : False, "resources" : 3, "influence" : 4, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Acquiescence Omega"],
		"leaders"		: {"agent" : [{"name" : "Berekar Berekon", "exhausted" : False}], 
						"commander" : [{"name" : "Rickar Rickani", "unlocked" : False}], 
						"hero" : [{"locked name" : "Mathis Mathinus", "unlocked name" : "Imperial Seal", "unlocked" : False}]}
	}, 
    "Xxcha"  	: {
		"maxComm" 		: 4,
		"technology" 	: ["Graviton Laser System"],
		"planets"		: {"Archon Ren" : {"exhausted" : False, "resources" : 2, "influence" : 3, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Archon Tau" : {"exhausted" : False, "resources" : 1, "influence" : 1, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Political Favor"],
		"leaders"		: {"agent" : [{"name" : "Ggrocuto Rinn", "exhausted" : False}], 
						"commander" : [{"name" : "Elder Qanoj", "unlocked" : False}], 
						"hero" : [{"locked name" : "Xxekir Grom", "unlocked name" : "Political Data Nexus", "unlocked" : False}]}
	}, 
    "Yin" 		: {
		"maxComm" 		: 2,
		"technology" 	: ["Sarween Tools"],
		"planets"		: {"Darien" : {"exhausted" : False, "resources" : 4, "influence" : 4, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Greyfire Mutagen Omega"],
		"leaders"		: {"agent" : [{"name" : "Brother Milor Omega", "exhausted" : False}], 
						"commander" : [{"name" : "Brother Omar Omega", "unlocked" : False}], 
						"hero" : [{"locked name" : "Dannel of the Tenth Omega", "unlocked name" : "Quantum Dissemination Omega", "unlocked" : False}]}
	}, 
    "Yssaril"  	: {
		"maxComm" 		: 3,
		"technology" 	: ["Neural Motivator"],
		"planets"		: {"Retillion" : {"exhausted" : False, "resources" : 2, "influence" : 3, "tech" : "", "leg" : False, "Trait" : "Home"},
							"Shalloq" : {"exhausted" : False, "resources" : 1, "influence" : 2, "tech" : "", "leg" : False, "Trait" : "Home"}},
		"promissoryNotes" : ["Spy Net"],
		"leaders"		: {"agent" : [{"name" : "Ssruu", "exhausted" : False}], 
						"commander" : [{"name" : "So Ata", "unlocked" : False}], 
						"hero" : [{"locked name" : "Kyver, Blade and Key", "unlocked name" : "Guild of Spies", "unlocked" : False}]}
	}, 
}

traits = ["home", "mecatolrex", "cultural", "industrial", "hazardous"]

planets = {
	"Jord" 			: {"exhausted" : True, 	"resources" : 4, 	"influence" : 2, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Moll Primus" 	: {"exhausted" : True, 	"resources" : 4, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Darien"		: {"exhausted" : True, 	"resources" : 4, 	"influence" : 4, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Muaat" 		: {"exhausted" : True, 	"resources" : 4, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Nestphar" 		: {"exhausted" : True, 	"resources" : 3, 	"influence" : 2, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"[0.0.0]" 		: {"exhausted" : True, 	"resources" : 5, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Winnu" 		: {"exhausted" : True, 	"resources" : 3, 	"influence" : 4, 	"tech" : "", 		"leg" : False, 	"Trait" : "home"},
	"Mordai II" 	: {"exhausted" : True,	"resources" : 4, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Druaa" 		: {"exhausted" : True,	"resources" : 3, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Maaluuk" 		: {"exhausted" : True,	"resources" : 0, 	"influence" : 2, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Arc Prime" 	: {"exhausted" : True,	"resources" : 4, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Wren Terra" 	: {"exhausted" : True,	"resources" : 2, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Lisis II" 		: {"exhausted" : True,	"resources" : 1, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Ragh" 			: {"exhausted" : True,	"resources" : 2, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Jol" 			: {"exhausted" : True,	"resources" : 1, 	"influence" : 2, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Nar" 			: {"exhausted" : True,	"resources" : 2, 	"influence" : 3, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Quinarra" 		: {"exhausted" : True,	"resources" : 3, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Tren'lak" 		: {"exhausted" : True,	"resources" : 1, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Archon Ren" 	: {"exhausted" : True,	"resources" : 2, 	"influence" : 3, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Archon Tau" 	: {"exhausted" : True,	"resources" : 1, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Retillion" 	: {"exhausted" : True,	"resources" : 2, 	"influence" : 3, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Shalloq" 		: {"exhausted" : True,	"resources" : 1, 	"influence" : 2, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Arretze" 		: {"exhausted" : True,	"resources" : 2, 	"influence" : 0, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Hercant" 		: {"exhausted" : True,	"resources" : 1, 	"influence" : 1, 	"tech" : "", 		"leg" : False, 	"trait" : "home"},
	"Kamdorn" 		: {"exhausted" : True,	"resources" : 0,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Mecatol Rex" 	: {"exhausted" : True,	"resources" : 1,	"influence" : 6,	"tech" : "",		"leg" : False, 	"trait" : "mecatolrex"},
	"Wellon" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "yellow",	"leg" : False, 	"trait" : "industrial"},
	"Vefut II" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Thibah" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "blue",	"leg" : False, 	"trait" : "industrial"},
	"Tar'mann" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "green",	"leg" : False, 	"trait" : "industrial"},
	"Saudor" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Mehar Xull" 	: {"exhausted" : True,	"resources" : 1,	"influence" : 3,	"tech" : "red",		"leg" : False, 	"trait" : "hazardous"},
	"Quann" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Lodor" 		: {"exhausted" : True,	"resources" : 3,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"New Albion" 	: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "green",	"leg" : False, 	"trait" : "industrial"},
	"Starpoint" 	: {"exhausted" : True,	"resources" : 3,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Tequ'ran" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Torkan" 		: {"exhausted" : True,	"resources" : 0,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Qucen'n" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Rarron" 		: {"exhausted" : True,	"resources" : 0,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Mellon" 		: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Zohbat" 		: {"exhausted" : True,	"resources" : 3,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Lazar" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 0,	"tech" : "yellow",	"leg" : False, 	"trait" : "industrial"},
	"Sakulag" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Dal Bootha" 	: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Xxehan" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Corneeq" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Resculon" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Centauri" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Gral" 			: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "blue",	"leg" : False, 	"trait" : "industrial"},
	"Bereg" 		: {"exhausted" : True,	"resources" : 3,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Lirta IV" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Arnor" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Lor" 			: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Arinam" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Meer" 			: {"exhausted" : True,	"resources" : 0,	"influence" : 4,	"tech" : "red",		"leg" : False, 	"trait" : "hazardous"},
	"Abyz" 			: {"exhausted" : True,	"resources" : 3,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Fria"	 		: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Creuss" 		: {"exhausted" : True,	"resources" : 4,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Ixth" 			: {"exhausted" : True,	"resources" : 3,	"influence" : 5,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Arcturus" 		: {"exhausted" : True,	"resources" : 4,	"influence" : 4,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Acheron" 		: {"exhausted" : True,	"resources" : 4,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Elysium" 		: {"exhausted" : True,	"resources" : 4,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"The Dark" 		: {"exhausted" : True,	"resources" : 3,	"influence" : 4,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Naazir" 		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Rokha" 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Avar" 			: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Valk" 			: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Ylir" 			: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "home"},
	"Archon Vail"	: {"exhausted" : True,	"resources" : 2,	"influence" : 3,	"tech" : "blue",	"leg" : False, 	"trait" : "hazardous"},
	"Perimeter"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Ang"	 		: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "red",		"leg" : False, 	"trait" : "industrial"},
	"Sem-Lore"	 	: {"exhausted" : True,	"resources" : 3,	"influence" : 2,	"tech" : "yellow",	"leg" : False, 	"trait" : "cultural"},
	"Vorhal"	 	: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "green",	"leg" : False, 	"trait" : "cultural"},
	"Atlas"	 		: {"exhausted" : True,	"resources" : 3,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Primor"		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : True, 	"trait" : "cultural"},
	"Hope's End"	: {"exhausted" : True,	"resources" : 3,	"influence" : 0,	"tech" : "",		"leg" : True, 	"trait" : "hazardous"},
	"Cormund"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Everra"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Accoen"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Jeol Ir"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 3,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Kraag"	 		: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Siig"	 		: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Alio Prima"	: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Ba'kal"	 	: {"exhausted" : True,	"resources" : 3,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Lisis"	 		: {"exhausted" : True,	"resources" : 2,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Velnor"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "red",		"leg" : False, 	"trait" : "industrial"},
	"Cealdri"	 	: {"exhausted" : True,	"resources" : 0,	"influence" : 2,	"tech" : "yellow",	"leg" : False, 	"trait" : "cultural"},
	"Xanhact"	 	: {"exhausted" : True,	"resources" : 0,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Vega Major"	: {"exhausted" : True,	"resources" : 2,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Vega Minor"	: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "blue",	"leg" : False, 	"trait" : "cultural"},
	"Abaddon"	 	: {"exhausted" : True,	"resources" : 1,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Ashtroth"	 	: {"exhausted" : True,	"resources" : 2,	"influence" : 0,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Loki"	 		: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "cultural"},
	"Rigel I"	 	: {"exhausted" : True,	"resources" : 0,	"influence" : 1,	"tech" : "",		"leg" : False, 	"trait" : "hazardous"},
	"Rigel II"	 	: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : False, 	"trait" : "industrial"},
	"Rigel III"	 	: {"exhausted" : True,	"resources" : 1,	"influence" : 1,	"tech" : "green",	"leg" : False, 	"trait" : "industrial"},
	"Mallice"	 	: {"exhausted" : True,	"resources" : 0,	"influence" : 3,	"tech" : "",		"leg" : True, 	"trait" : "cultural"},
	"Mirage"	 	: {"exhausted" : True,	"resources" : 1,	"influence" : 2,	"tech" : "",		"leg" : True, 	"trait" : "cultural"},
	"Custodia Vigilia": {"exhausted" : True,"resources" : 2,	"influence" : 3,	"tech" : "",		"leg" : True, 	"trait" : "none"},
}

systems = {
	1 : ['Jord'],
	2 : ['Moll Primus'], 
	3 : ['Darien'], 
	4 : ['Muaat'], 
	5 : ['Nestphar'], 
	6 : ['[0.0.0]'], 
	7 : ['Winnu'], 
	8 : ['Mordai II'], 
	9 : ['Druaa', 'Maaluuk'], 
	10: ['Arc Prime', 'Wren Terra'], 
	11: ['Lisis II', 'Ragh'], 
	12: ['Jol', 'Nar'], 
	13: ['Quinarra', "Tren'lak"], 
	14: ['Archon Ren', 'Archon Tau'], 
	15: ['Retillion', 'Shalloq'], 
	16: ['Arretze', 'Hercant', 'Kamdorn'], 
	18: ['Mecatol Rex'], 
	19: ['Wellon'], 
	20: ['Vefut II'], 
	21: ['Thibah'], 
	22: ["Tar'mann"], 
	23: ['Saudor'], 
	24: ['Mehar Xull'], 
	25: ['Quann'], 
	26: ['Lodor'], 
	27: ['New Albion', 'Starpoint'], 
	28: ["Tequ'ran", 'Torkan'], 
	29: ["Qucen'n", 'Rarron'], 
	30: ['Mellon', 'Zohbat'], 
	31: ['Lazar', 'Sakulag'], 
	32: ['Dal Bootha', 'Xxehan'], 
	33: ['Corneeq', 'Resculon'], 
	34: ['Centauri', 'Gral'], 
	35: ['Bereg', 'Lirta IV'], 
	36: ['Arnor', 'Lor'], 
	37: ['Arinam', 'Meer'], 
	38: ['Abyz', 'Fria'], 
	51: ['Creuss'], 
	52: ['Ixth'], 
	53: ['Arcturus'], 
	54: ['Acheron'], 
	55: ['Elysium'], 
	56: ['The Dark'], 
	57: ['Naazir', 'Rokha'], 
	58: ['Avar', 'Valk', 'Ylir'], 
	59: ['Archon Vail'], 
	60: ['Perimeter'], 
	61: ['Ang'],
	62: ['Sem-Lore'], 
	63: ['Vorhal'], 
	64: ['Atlas'], 
	65: ['Primor'], 
	66: ["Hope's End"], 
	67: ['Cormund'], 
	68: ['Everra'], 
	69: ['Accoen', 'Jeol Ir'], 
	70: ['Kraag', 'Siig'], 
	71: ["Ba'kal", 'Alio Prima'], 
	72: ['Lisis', 'Velnor'], 
	73: ['Cealdri', 'Xanhact'], 
	74: ['Vega Major', 'Vega Minor'], 
	75: ['Abaddon', 'Ashtroth', 'Loki'], 
	76: ['Rigel I', 'Rigel II', 'Rigel III'], 
	82: ['Mallice'],
}

modalSpaceFleetTemplate = '''
Flagship : 0
Warsun : 0
Dreadnought : 0
Carrier : 0
Cruiser : 0
Destroyer : 0
Fighter : 0
Infantry : 0
Mech : 0
TeamHSID : 0
'''
modalPlanetFleetTemplate = '''
Planet : [PLANETNAME]
PDS : 0
Infantry : 0
Spacedock : 0
Mech : 0
Control Token : 0
TeamHSID : 0
'''

timezones = {
	"ACDT":"10:30","ACST":"9:30","ACWST":"8:45","ADT":"4:00","AEDT":"11:00","AEST":"10:00","AFT":"4:30","AKDT":"-8:00",
	"AKST":"-9:00","ALMT":"6:00","AMST":"5:00","AMT":"4:00","ANAST":"12:00","ANAT":"12:00","AQTT":"5:00","ART":"-3:00",
	"AST":"3:00","AWDT":"9:00","AWST":"8:00","AZOST":"0:00","AZOT":"-1:00","AZST":"5:00","AZT":"4:00","BNT":"8:00",
	"BOT":"-4:00","BRST":"-2:00","BRT":"-3:00","BST":"1:00","BTT":"6:00","CAST":"8:00","CAT":"2:00","CCT":"6:30",
	"CDT":"-5:00","CEST":"2:00","CET":"1:00","CHADT":"13:45","CHAST":"12:45","CHOST":"9:00","CHOT":"8:00","CHUT":"10:00",
	"CIDST":"-4:00","CIST":"-5:00","CKT":"-10:00","CLST":"-3:00","CLT":"-4:00","COT":"-5:00","CST":"-6:00","CVT":"-1:00",
	"CXT":"7:00","ChST":"10:00","DAVT":"7:00","DDUT":"10:00","EASST":"-5:00","EAST":"-6:00","EAT":"3:00","ECT":"-5:00",
	"EDT":"-4:00","EEST":"3:00","EET":"2:00","EGST":"0:00","EGT":"-1:00","EST":"-5:00","FET":"3:00","FJST":"13:00",
	"FJT":"12:00","FKST":"-3:00","FKT":"-4:00","FNT":"-2:00","GALT":"-6:00","GAMT":"-9:00","GET":"4:00","GFT":"-3:00",
	"GILT":"12:00","GMT":"0:00","GST":"4:00","GYT":"-4:00","HDT":"-9:00","HKT":"8:00","HOVST":"8:00","HOVT":"7:00",
	"HST":"-10:00","ICT":"7:00","IDT":"3:00","IOT":"6:00","IRDT":"4:30","IRKST":"9:00","IRKT":"8:00","IRST":"3:30",
	"IST":"5:30","JST":"9:00","KGT":"6:00","KOST":"11:00","KRAST":"8:00","KRAT":"7:00","KST":"9:00","KUYT":"4:00",
	"LHDT":"11:00","LHST":"10:30","LINT":"14:00","MAGST":"12:00","MAGT":"11:00","MART":"-9:30","MAWT":"5:00","MDT":"-6:00",
	"MHT":"12:00","MMT":"6:30","MSD":"4:00","MSK":"3:00","MST":"-7:00","MUT":"4:00","MVT":"5:00","MYT":"8:00",
	"NCT":"11:00","NDT":"-2:30","NFT":"11:00","NOVST":"7:00","NOVT":"6:00","NPT":"5:45","NRT":"12:00","NST":"-3:30",
	"NUT":"-11:00","NZDT":"13:00","NZST":"12:00","OMSST":"7:00","OMST":"6:00","ORAT":"5:00","PDT":"-7:00","PET":"-5:00",
	"PETST":"12:00","PETT":"12:00","PGT":"10:00","PHOT":"13:00","PHT":"8:00","PKT":"5:00","PMDT":"-2:00","PMST":"-3:00",
	"PONT":"11:00","PST":"-8:00","PWT":"9:00","PYST":"-3:00","PYT":"-4:00","QYZT":"6:00","RET":"4:00","ROTT":"-3:00",
	"SAKT":"11:00","SAMT":"4:00","SAST":"2:00","SBT":"11:00","SCT":"4:00","SGT":"8:00","SRET":"11:00","SRT":"-3:00",
	"SST":"-11:00","SYOT":"3:00","TAHT":"-10:00","TFT":"5:00","TJT":"5:00","TKT":"13:00","TLT":"9:00","TMT":"5:00",
	"TOST":"14:00","TOT":"13:00","TRT":"3:00","TVT":"12:00","ULAST":"9:00","ULAT":"8:00","UTC":"0:00","UYST":"-2:00",
	"UYT":"-3:00","UZT":"5:00","VET":"-4:00","VLAST":"11:00","VLAT":"10:00","VOST":"6:00","VUT":"11:00","WAKT":"12:00",
	"WARST":"-3:00","WAST":"2:00","WAT":"1:00","WEST":"1:00","WET":"0:00","WFT":"12:00","WGST":"-2:00","WGT":"-3:00",
	"WIB":"7:00","WIT":"9:00","WITA":"8:00","WST":"1:00","WT":"0:00","YAKST":"10:00","YAKT":"9:00","YAPT":"10:00",
	"YEKST":"6:00","YEKT":"5:00",
}

topleveldomains = {
	"JAVA",	"RUHR",	"HONDA",	"PICTET",	"CYOU",	"SWISS",	"AO",	"TRAVELERS",	
	"TRAVELERS",	"AUDI",	"OOO",	"PING",	"TRADING",	"SAMSUNG",	"TG",	"AIG",	
	"ARCHI",	"CALL",	"SANDVIK",	"ASIA",	"HOW",	"MAKEUP",	"NYC",	"MOTORCYCLES",	
	"HERMES",	"JCB",	"DHL",	"CRS",	"VIP",	"DIRECTORY",	"COOKING",	"REVIEWS",	
	"OM",	"ARAB",	"PARTS",	"REPUBLICAN",	"LAWYER",	"NR",	"BO",	"VOYAGE",	
	"CLAIMS",	"NORTON",	"LA",	"DIY",	"STOCKHOLM",	"GLOBAL",	"SLING",	"TOP",	
	"TV",	"SK",	"LPL",	"GD",	"KRED",	"CFD",	"READ",	"SILK",	
	"BANAMEX",	"ONE",	"HIV",	"CODES",	"BOX",	"LEGAL",	"WED",	"DM",	
	"VU",	"TK",	"SOCIAL",	"SPOT",	"DAD",	"OFFICE",	"CAREERS",	"PORN",	
	"CV",	"MOV",	"WOW",	"MADRID",	"MR",	"AUDIBLE",	"CLOUD",	"LUNDBECK",	
	"FOOTBALL",	"SAFETY",	"LLC",	"SHOP",	"CAB",	"VERISIGN",	"TODAY",	"FINANCE",	
	"FO",	"LINK",	"BAR",	"CO",	"ACO",	"PROPERTIES",	"AT",	"LAMER",	
	"OBI",	"PARTY",	"IMAMAT",	"TATAR",	"AI",	"TIENDA",	"DIGITAL",	"PS",	
	"VOLVO",	"FTR",	"NU",	"MODA",	"NE",	"TD",	"ET",	"LAT",	
	"WF",	"CLINIC",	"SOY",	"JP",	"GR",	"FLICKR",	"RE",	"VIKING",	
	"SEEK",	"LU",	"SAS",	"TATTOO",	"BW",	"STCGROUP",	"BZH",	"ICBC",	
	"SA",	"ARTE",	"SANOFI",	"PH",	"CI",	"BY",	"VISA",	"REISEN",	
	"KYOTO",	"ARMY",	"EXPOSED",	"STAPLES",	"NL",	"BAYERN",	"SPORT",	"BASEBALL",	
	"CD",	"DOG",	"FUN",	"EVENTS",	"ROGERS",	"DO",	"NTT",	"DELTA",	
	"BF",	"REISE",	"MT",	"HEALTHCARE",	"DATE",	"CATHOLIC",	"DELOITTE",	"TOURS",	
	"ORGANIC",	"CM",	"SN",	"CREDITCARD",	"LDS",	"HOTELS",	"SYSTEMS",	"MTR",	
	"SINGLES",	"REXROTH",	"BOOK",	"ANALYTICS",	"CATERING",	"LANDROVER",	"BBC",	"KOSHER",	
	"BRIDGESTONE",	"ONG",	"VIRGIN",	"WEIR",	"PT",	"LI",	"BRADESCO",	"PRESS",	
	"IS",	"CAT",	"BBT",	"FREE",	"IFM",	"SENER",	"HIPHOP",	"WANGGOU",	
	"DESI",	"AS",	"SALE",	"ZERO",	"RACING",	"PROF",	"PROGRESSIVE",	"LOAN",	
	"LASALLE",	"YOGA",	"CHINTAI",	"LIVE",	"TEL",	"LAND",	"COACH",	"BAND",	
	"TH",	"VIAJES",	"MED",	"SEARCH",	"MANAGEMENT",	"SM",	"MA",	"SHOW",	
	"EU",	"LOANS",	"GA",	"BB",	"PHOTO",	"JE",	"WALMART",	"HEALTH",	
	"HERE",	"SEAT",	"RU",	"CASA",	"UBANK",	"ZUERICH",	"AUCTION",	"JM",	
	"WORLD",	"AUDIO",	"HOLIDAY",	"SOLAR",	"BH",	"RW",	"ALLFINANZ",	"CRUISE",	
	"BR",	"ITAU",	"AR",	"SPACE",	"KI",	"FITNESS",	"SECURITY",	"DCLK",	
	"SNCF",	"NOWTV",	"YUN",	"SE",	"CAMERA",	"CBRE",	"COMMBANK",	"GQ",	
	"WS",	"PIONEER",	"ORANGE",	"PF",	"AU",	"TICKETS",	"OMEGA",	"AIRTEL",	
	"TATAMOTORS",	"SONY",	"COLOGNE",	"SAMSCLUB",	"MARKET",	"SONG",	"ART",	"GRAPHICS",	
	"RIO",	"PICS",	"BMW",	"ANZ",	"PCCW",	"CITADEL",	"BEATS",	"WEBCAM",	
	"REALTY",	"HITACHI",	"GP",	"DIRECT",	"MEN",	"ABOGADO",	"HISAMITSU",	"TRAINING",	
	"PG",	"FASHION",	"SAVE",	"GG",	"GAL",	"KZ",	"HSBC",	"DATING",	
	"BBVA",	"DATA",	"TUBE",	"CARE",	"ATHLETA",	"BRUSSELS",	"BOND",	"DESIGN",	
	"TAX",	"LEXUS",	"LILLY",	"SURGERY",	"SG",	"CHURCH",	"GOLD",	"STUDY",	
	"FARM",	"BID",	"EPSON",	"VIVA",	"VOTO",	"CAPITAL",	"PANASONIC",	"UZ",	
	"ALIBABA",	"SEW",	"FORD",	"SOFTBANK",	"PRO",	"DELL",	"BUILDERS",	"XIN",	
	"AD",	"MENU",	"BANK",	"PUB",	"PHOTOGRAPHY",	"RICHARDLI",	"CASH",	"NEW",	
	"CARS",	"EXTRASPACE",	"AQ",	"LS",	"POST",	"JOBS",	"JOY",	"LANCASTER",	
	"FERRARI",	"HU",	"SCHMIDT",	"STC",	"NI",	"GOODYEAR",	"GUITARS",	"AW",	
	"DUNLOP",	"CARDS",	"NEUSTAR",	"ERICSSON",	"ER",	"STREAM",	"PARIS",	"LOTTE",	
	"VANA",	"MONEY",	"PLAY",	"KPMG",	"CALVINKLEIN",	"IBM",	"JIO",	"CG",	
	"NAB",	"SUPPLY",	"ENERGY",	"AIRBUS",	"CHRISTMAS",	"SBS",	"BD",	"ORG",	
	"LEASE",	"LECLERC",	"DOT",	"SARL",	"APARTMENTS",	"AX",	"BIZ",	"MO",	
	"DOMAINS",	"SX",	"BI",	"LOL",	"ANQUAN",	"AZ",	"SMART",	"BS",	
	"IRISH",	"GREEN",	"FRL",	"CHEAP",	"TJMAXX",	"TJX",	"PRU",	"AMAZON",	
	"FISH",	"MLB",	"RODEO",	"CASE",	"YODOBASHI",	"FUND",	"VANGUARD",	"MINI",	
	"UG",	"BASKETBALL",	"PRUDENTIAL",	"SCOT",	"ICU",	"AFRICA",	"AMICA",	"COMSEC",	
	"DVR",	"KN",	"MONSTER",	"HOMEGOODS",	"BARCLAYS",	"SO",	"MX",	"FM",	
	"YANDEX",	"HR",	"MIT",	"CONSTRUCTION",	"BLACK",	"BLOG",	"STYLE",	"BOATS",	
	"HKT",	"SJ",	"BARCELONA",	"SFR",	"SINA",	"NRA",	"EE",	"HANGOUT",	
	"TUNES",	"SOHU",	"KUOKGROUP",	"ARAMCO",	"BEST",	"LIFE",	"GUCCI",	"ACADEMY",	
	"CHASE",	"SCHULE",	"BAUHAUS",	"TZ",	"BARCLAYCARD",	"ALSACE",	"LEGO",	"XN",	
	"SV",	"PHOTOS",	"STADA",	"NOWRUZ",	"BLOOMBERG",	"VET",	"NISSAN",	"CZ",	
	"TF",	"BAREFOOT",	"AM",	"RUGBY",	"BG",	"DJ",	"SPA",	"DANCE",	
	"DISCOUNT",	"SC",	"JEWELRY",	"NEC",	"MOBILE",	"LIKE",	"YOU",	"IT",	
	"AERO",	"INTERNATIONAL",	"XIHUAN",	"MAN",	"LTDA",	"SR",	"DEAL",	"ORACLE",	
	"CU",	"HYUNDAI",	"NFL",	"NINJA",	"BM",	"SKY",	"UNIVERSITY",	"NAVY",	
	"TDK",	"IE",	"RENTALS",	"ABBOTT",	"FOO",	"INT",	"JOT",	"IQ",	
	"EG",	"YAHOO",	"CX",	"CLINIQUE",	"ISTANBUL",	"GLE",	"EQUIPMENT",	"PHILIPS",	
	"CPA",	"PAGE",	"SMILE",	"ABUDHABI",	"GENT",	"HK",	"COUNTRY",	"CREDITUNION",	
	"GBIZ",	"BHARTI",	"UBS",	"REHAB",	"COURSES",	"POKER",	"BMS",	"AFL",	
	"CONTACT",	"GIFTS",	"SHOUJI",	"NBA",	"BLOCKBUSTER",	"WOODSIDE",	"DOCS",	"TC",	
	"GODADDY",	"GMX",	"SHELL",	"FARMERS",	"NEXT",	"NA",	"FLOWERS",	"OPEN",	
	"PWC",	"NOKIA",	"GOLF",	"RUN",	"BEAUTY",	"FIT",	"LAMBORGHINI",	"SAFE",	
	"SUCKS",	"WINNERS",	"REDUMBRELLA",	"PET",	"GOO",	"TRAVEL",	"REN",	"DK",	
	"GOLDPOINT",	"BE",	"IM",	"AETNA",	"SHIA",	"AMERICANEXPRESS",	"RICH",	"SECURE",	
	"JOBURG",	"SI",	"AKDN",	"LANXESS",	"NP",	"SURF",	"RELIANCE",	"SOLUTIONS",	
	"LIMO",	"CF",	"QUEBEC",	"LPLFINANCIAL",	"TKMAXX",	"EAT",	"TEMASEK",	"CLUB",	
	"HELSINKI",	"PM",	"BESTBUY",	"DZ",	"GIVING",	"QA",	"EMAIL",	"MBA",	
	"FAGE",	"VIN",	"ID",	"FRONTIER",	"COFFEE",	"GW",	"SL",	"MOE",	
	"GF",	"BOSTON",	"WINE",	"ENGINEERING",	"WIKI",	"THEATER",	"ABBVIE",	"FINANCIAL",	
	"PICTURES",	"GM",	"GDN",	"HOCKEY",	"CN",	"TRV",	"GAP",	"MC",	
	"IN",	"FOREX",	"TCI",	"BEER",	"WALTER",	"HOMES",	"FROGANS",	"RENT",	
	"MEMORIAL",	"DISCOVER",	"WTC",	"BET",	"RICOH",	"SCIENCE",	"MOBI",	"INFINITI",	
	"ADULT",	"DE",	"XEROX",	"ME",	"MLS",	"BOSCH",	"AMERICANFAMILY",	"ATTORNEY",	
	"CBA",	"NO",	"SEVEN",	"ALLY",	"UA",	"SWATCH",	"CITI",	"ROOM",	
	"IEEE",	"HOST",	"KIA",	"CAMP",	"DAY",	"ACTOR",	"OBSERVER",	"LOCKER",	
	"UNICOM",	"POHL",	"PFIZER",	"CREDIT",	"KIDS",	"SD",	"LTD",	"NGO",	
	"FOUNDATION",	"AL",	"FORSALE",	"TM",	"ZIP",	"GMBH",	"PW",	"KPN",	
	"MORMON",	"MAIF",	"DENTAL",	"BUZZ",	"FJ",	"SS",	"MY",	"SEX",	
	"GU",	"KERRYLOGISTICS",	"US",	"BLACKFRIDAY",	"CFA",	"EDU",	"EUS",	"CA",	
	"RO",	"TECH",	"YE",	"FAMILY",	"KOMATSU",	"LATROBE",	"NET",	"PHYSIO",	
	"TT",	"TRADE",	"LATINO",	"TAOBAO",	"DOWNLOAD",	"GOT",	"PN",	"MEME",	
	"PHONE",	"BUY",	"PROD",	"LIGHTING",	"REST",	"CORSICA",	"TOOLS",	"FAN",	
	"OTT",	"KIM",	"DUBAI",	"WATCH",	"KH",	"NZ",	"DISH",	"CAL",	
	"IMDB",	"SHOES",	"LY",	"BARGAINS",	"ALSTOM",	"STUDIO",	"DURBAN",	"SRL",	
	"COOL",	"GALLERY",	"WORK",	"WEBSITE",	"NETBANK",	"WEATHERCHANNEL",	"LIFESTYLE",	"SZ",	
	"FAIRWINDS",	"ZA",	"CRUISES",	"SKIN",	"GENTING",	"DEALS",	"KINDLE",	"REPORT",	
	"MEET",	"VN",	"TOSHIBA",	"WINDOWS",	"ML",	"NICO",	"TIROL",	"YACHTS",	
	"RADIO",	"CLEANING",	"PR",	"MITSUBISHI",	"MD",	"NRW",	"TRUST",	"GGEE",	
	"GN",	"WEDDING",	"STORE",	"MMA",	"FYI",	"AARP",	"UY",	"MOTO",	
	"CAFE",	"RESTAURANT",	"LIMITED",	"COM",	"PLAYSTATION",	"XYZ",	"SUPPLIES",	"RWE",	
	"MIAMI",	"GY",	"ZAPPOS",	"ONLINE",	"CRICKET",	"CAM",	"GURU",	"CLUBMED",	
	"TALK",	"WANG",	"LOTTO",	"CIRCLE",	"GIFT",	"INK",	"CONDOS",	"FK",	
	"KERRYPROPERTIES",	"KM",	"LV",	"AE",	"AGENCY",	"JMP",	"PRIME",	"RECIPES",	
	"ABB",	"BUSINESS",	"AG",	"MORTGAGE",	"FIRE",	"BOOKING",	"MN",	"YOUTUBE",	
	"NETFLIX",	"MAISON",	"ICE",	"GMAIL",	"JAGUAR",	"PLUMBING",	"LEFRAK",	"ASDA",	
	"AGAKHAN",	"GOP",	"DATSUN",	"GE",	"BV",	"CR",	"MINT",	"LIFEINSURANCE",	
	"VLAANDEREN",	"WALES",	"INVESTMENTS",	"MIL",	"AMEX",	"NF",	"QPON",	"HDFC",	
	"BROKER",	"CONTRACTORS",	"FAST",	"BZ",	"IKANO",	"KAUFEN",	"WEIBO",	"BN",	
	"VENTURES",	"MARKETS",	"EXCHANGE",	"TRAVELERSINSURANCE",	"TUSHU",	"HYATT",	"GL",	"VEGAS",	
	"TN",	"SALON",	"UNO",	"COLLEGE",	"GH",	"DIET",	"VIVO",	"COMPARE",	
	"NAGOYA",	"WOLTERSKLUWER",	"PROMO",	"TIPS",	"ARPA",	"KG",	"CHAT",	"QUEST",	
	"CUISINELLA",	"CERN",	"CANON",	"FLIGHTS",	"PINK",	"WHOSWHO",	"DNP",	"INFO",	
	"LOVE",	"MARSHALLS",	"FANS",	"MOVIE",	"BJ",	"XBOX",	"BIBLE",	"FIDO",	
	"SOCCER",	"SCHAEFFLER",	"KERRYHOTELS",	"SAXO",	"ADS",	"COMPUTER",	"FUTBOL",	"TORAY",	
	"NETWORK",	"BUILD",	"TAB",	"FERRERO",	"BROTHER",	"TIAA",	"MTN",	"MUSIC",	
	"CISCO",	"VILLAS",	"DELIVERY",	"MU",	"STAR",	"CASINO",	"REALTOR",	"LONDON",	
	"HOT",	"AAA",	"MUSEUM",	"TOKYO",	"PRAXI",	"SHARP",	"KY",	"MCKINSEY",	
	"ZM",	"FAIL",	"CENTER",	"JPRS",	"BIKE",	"ASSOCIATES",	"KP",	"VI",	
	"NEXTDIRECT",	"DEMOCRAT",	"COMPANY",	"STORAGE",	"VIG",	"GROUP",	"SANDVIKCOROMANT",	"AF",	
	"COMMUNITY",	"CH",	"HBO",	"CITY",	"FORUM",	"KFH",	"ROCKS",	"COOP",	
	"OKINAWA",	"GOOGLE",	"MM",	"GLASS",	"CEO",	"CAPITALONE",	"ACCOUNTANTS",	"POLITIE",	
	"HELP",	"INSURE",	"IMMOBILIEN",	"HOMEDEPOT",	"MG",	"APPLE",	"JUNIPER",	"AZURE",	
	"COUPONS",	"GIVES",	"BROADWAY",	"CLOTHING",	"CHROME",	"HORSE",	"FAITH",	"CARAVAN",	
	"MOM",	"FEEDBACK",	"AUTHOR",	"LK",	"PY",	"INTUIT",	"VOTE",	"PHARMACY",	
	"SHANGRILA",	"RIL",	"FIRMDALE",	"BT",	"SCHOLARSHIPS",	"MQ",	"BOUTIQUE",	"FIRESTONE",	
	"NIKE",	"VODKA",	"DUPONT",	"CHARITY",	"MZ",	"GOOG",	"DENTIST",	"TARGET",	
	"CL",	"TMALL",	"AWS",	"REPAIR",	"VA",	"GARDEN",	"SAKURA",	"JPMORGAN",	
	"ST",	"AXA",	"EDEKA",	"PLACE",	"HOLDINGS",	"RSVP",	"TIRES",	"GLOBO",	
	"TVS",	"WIEN",	"PL",	"ALIPAY",	"REALESTATE",	"LOCUS",	"ZONE",	"VE",	
	"KRD",	"AC",	"DRIVE",	"PARS",	"WME",	"DEALER",	"FRESENIUS",	"IO",	
	"BAIDU",	"SH",	"INSURANCE",	"JNJ",	"NHK",	"PE",	"ENGINEER",	"UOL",	
	"GAY",	"WEATHER",	"INC",	"MOSCOW",	"COUPON",	"AUSPOST",	"ERNI",	"TOTAL",	
	"VISION",	"CYMRU",	"MARRIOTT",	"EUROVISION",	"BLUE",	"BABY",	"ORIGINS",	"SITE",	
	"LIDL",	"ACCOUNTANT",	"INSTITUTE",	"CBN",	"KW",	"MK",	"MANGO",	"HAIR",	
	"SERVICES",	"CIPRIANI",	"MP",	"CHANNEL",	"BENTLEY",	"TUI",	"SHOPPING",	"SEXY",	
	"EDUCATION",	"LUXE",	"GRIPE",	"LUXURY",	"ECO",	"LLP",	"AIRFORCE",	"PROTECTION",	
	"FUJITSU",	"DOCTOR",	"SUPPORT",	"RED",	"TENNIS",	"NOW",	"BA",	"OLAYAN",	
	"MV",	"GI",	"BOO",	"BCG",	"PRAMERICA",	"FILM",	"ZW",	"RIP",	
	"ITV",	"TAIPEI",	"SAP",	"AUTOS",	"AMSTERDAM",	"EXPERT",	"GAME",	"OLAYANGROUP",	
	"GT",	"LIVING",	"YOKOHAMA",	"CK",	"HM",	"KIWI",	"IR",	"HAUS",	
	"CONSULTING",	"BOFA",	"SY",	"TEVA",	"HDFCBANK",	"NAME",	"FEDEX",	"BOT",	
	"PROPERTY",	"VIDEO",	"STATEBANK",	"LGBT",	"NISSAY",	"SCHWARZ",	"MW",	"PIN",	
	"WILLIAMHILL",	"IPIRANGA",	"MH",	"NG",	"ABLE",	"DIAMONDS",	"PIZZA",	"FLORIST",	
	"HT",	"MAP",	"SYDNEY",	"SHIKSHA",	"FURNITURE",	"KR",	"NEXUS",	"TO",	
	"TW",	"BINGO",	"MARKETING",	"ENTERPRISES",	"DVAG",	"SOFTWARE",	"MATTEL",	"LIPSY",	
	"UPS",	"AOL",	"PRODUCTIONS",	"TOWN",	"GS",	"FLY",	"FR",	"SU",	
	"MICROSOFT",	"CROWN",	"ABC",	"PAY",	"OLLO",	"CITIC",	"CHANEL",	"HUGHES",	
	"BCN",	"THD",	"GAMES",	"PARTNERS",	"VERSICHERUNG",	"GEORGE",	"DEV",	"LR",	
	"OVH",	"RYUKYU",	"DTV",	"FISHING",	"YT",	"VG",	"RS",	"GRAINGER",	
	"MEDIA",	"GEA",	"JLL",	"ZARA",	"HOMESENSE",	"GRATIS",	"MS",	"EC",	
	"DEGREE",	"TJ",	"UK",	"GOV",	"HOTMAIL",	"FI",	"ESTATE",	"MSD",	
	"SBI",	"PLUS",	"SCB",	"PHD",	"AQUARELLE",	"KE",	"CAREER",	"TL",	
	"BIO",	"WORKS",	"ANDROID",	"MONASH",	"HOUSE",	"MOI",	"MELBOURNE",	"KITCHEN",	
	"ONL",	"GROCERY",	"SELECT",	"JEEP",	"HAMBURG",	"ESQ",	"GALLO",	"TOYS",	
	"GMO",	"BNPPARIBAS",	"FLIR",	"NEWS",	"HN",	"SCHOOL",	"REIT",	"AMFAM",	
	"TECHNOLOGY",	"BING",	"REDSTONE",	"APP",	"ACCENTURE",	"BOSTIK",	"OTSUKA",	"LINCOLN",	
	"ISMAILI",	"EARTH",	"GUIDE",	"WIN",	"LT",	"GALLUP",	"SUZUKI",	"TAXI",	
	"CAPETOWN",	"BERLIN",	"BOM",	"TOYOTA",	"AEG",	"ES",	"LB",	"INDUSTRIES",	
	"CC",	"EXPRESS",	"GUGE",	"AUTO",	"JETZT",	"BOEHRINGER",	"CLICK",	"FOX",	
	"JUEGOS",	"VOTING",	"LC",	"XXX",	"GB",	"IL",	"YAMAXUN",	"VC",	
	"MERCKMSD",	"TR",	"LAW",	"IMMO",	"HOSPITAL",	"SB",	"KDDI",	"STATEFARM",	
	"SKI",	"THEATRE",	"IST",	"CAR",	"CY",	"SKYPE",	"ING",	"PID",	
	"JO",	"DDS",	"REVIEW",	"FINAL",	"NIKON",	"PNC",	"NC",	"PK",	
	"OSAKA",	"PA",	"CW",	"FIDELITY",	"KOELN",	"WTF",	"HOSTING",	"TEAM",	
	"EMERCK",	"VACATIONS",	"LACAIXA",	"FOOD",	"WATCHES",	"SAARLAND",	"ALLSTATE",	"WEBER",
}

lookupTileValues = {
	"1": [4, 0, []],
	"2": [4, 0, []],
	"3": [4, 4, []],
	"4": [4, 0, []],
	"5": [3, 0, []],
	"6": [5, 0, []],
	"7": [0, 4, []],
	"8": [4, 0, []],
	"9": [3, 2, []],
	"10": [6, 0, []],
	"11": [3, 0, []],
	"12": [0, 5, []],
	"13": [4, 0, []],
	"14": [1, 4, []],
	"15": [0, 5, []],
	"16": [3, 2, []],
	"17": [0, 0, ["δ"]],
	"18": [0, 6, []],
	"19": [0, 2, ["y"]],
	"20": [2, 2, []],
	"21": [1, 1, ["b"]],
	"22": [1, 1, ["g"]],
	"23": [2, 2, []],
	"24": [0, 3, ["r"]],
	"25": [2, 0, ["α"]],
	"26": [3, 0, ["β"]],
	"27": [4, 1, ["g"]],
	"28": [2, 3, []],
	"29": [0, 5, []],
	"30": [3, 2, []],
	"31": [3, 0, ["y"]],
	"32": [1, 3, []],
	"33": [2, 2, []],
	"34": [1, 4, ["b"]],
	"35": [3, 3, []],
	"36": [2, 2, []],
	"37": [0, 6, ["r"]],
	"38": [5, 0, []],
	"39": [0, 0, ["α"]],
	"40": [0, 0, ["β"]],
	"41": [0, 0, []],
	"42": [0, 0, []],
	"43": [0, 0, []],
	"44": [0, 0, []],
	"45": [0, 0, []],
	"46": [0, 0, []],
	"47": [0, 0, []],
	"48": [0, 0, []],
	"49": [0, 0, ["δ"]],
	"50": [0, 0, []],
	"51": [4, 0, []],
	"52": [0, 5, []],
	"53": [4, 4, []],
	"54": [4, 0, []],
	"55": [4, 0, []],
	"56": [0, 4, []],
	"57": [2, 2, []],
	"58": [3, 3, []],
	"59": [0, 3, ["b"]],
	"60": [2, 0, []],
	"61": [2, 0, ["r"]],
	"62": [3, 0, ["y"]],
	"63": [0, 2, ["g"]],
	"64": [3, 0, ["β"]],
	"65": [2, 0, ["L"]],
	"66": [3, 0, ["L"]],
	"67": [2, 0, []],
	"68": [3, 0, []],
	"69": [0, 6, []],
	"70": [2, 2, []],
	"71": [4, 1, []],
	"72": [4, 2, ["r"]],
	"73": [0, 3, ["y"]],
	"74": [2, 2, ["b"]],
	"75": [3, 2, []],
	"76": [1, 4, ["g"]],
	"77": [0, 0, []],
	"78": [0, 0, []],
	"79": [0, 0, ["α"]],
	"80": [0, 0, []],
	"81": [0, 0, []],
	"82": [0, 3, ["α", "β", "γ", "L"]],
}

startingFleets = {
	"Arborec" 	: {"carrier" : 1, "cruiser" : 1, "fighter" : 2, "infantry" : 4, "spacedock" : 1, "pds" : 1},
	"Argent" 	: {"carrier" : 1, "destroyer" : 2, "fighter" : 2, "infantry" : 5, "spacedock" : 1, "pds" : 1},
	"Barony"  	: {"dreadnought" : 1, "carrier" : 1, "destroyer" : 1, "fighter" : 1, "infantry" : 3, "spacedock" : 1},
	"Cabal" 	: {"dreadnought" : 1, "carrier" : 1, "cruiser" : 1, "fighter" : 3, "infantry" : 3, "spacedock" : 1},
    "Empyrean" 	: {"carrier" : 2, "destroyer" : 1, "fighter" : 2, "infantry" : 4, "spacedock" : 1},
    "Ghosts"  	: {"carrier" : 1, "destroyer" : 2, "fighter" : 2, "infantry" : 4, "spacedock" : 1},
    "Hacan" 	: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 4, "spacedock" : 1},
    "Jol-Nar"  	: {"dreadnought" : 1, "carrier" : 2, "fighter" : 1, "infantry" : 2, "spacedock" : 1, "pds" : 2},
    "Keleres [Argent]" 	: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 2, "spacedock" : 1},
    "Keleres [Mentak]" 	: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 2, "spacedock" : 1},
    "Keleres [Xxcha]" 	: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 2, "spacedock" : 1},
    "L1Z1X" 	: {"dreadnought" : 1, "carrier" : 1, "fighter" : 3, "infantry" : 5, "spacedock" : 1, "pds" : 1},
    "Mahact"  	: {"dreadnought" : 1, "carrier" : 1, "cruiser" : 1, "fighter" : 2, "infantry" : 3, "spacedock" : 1},
    "Mentak"  	: {"carrier" : 1, "cruiser" : 2, "fighter" : 3, "infantry" : 4, "spacedock" : 1, "pds" : 1},
    "Muaat"  	: {"warsun" : 1, "fighter" : 2, "infantry" : 4, "spacedock" : 1},
    "Naalu" 	: {"carrier" : 1, "cruiser" : 1, "destroyer" : 1, "fighter" : 3, "infantry" : 4, "spacedock" : 1, "pds" : 1},
    "Naaz-Rokha": {"carrier" : 2, "destroyer" : 1, "fighter" : 2, "mech" : 1, "infantry" : 3, "spacedock" : 1},
    "Nekro"  	: {"dreadnought" : 1, "carrier" : 1, "cruiser" : 1, "fighter" : 2, "infantry" : 2, "spacedock" : 1},
    "Nomad"  	: {"flagship" : 1, "carrier" : 1, "destroyer" : 1, "fighter" : 3, "infantry" : 4, "spacedock" : 1},
    "Saar" 		: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 4, "spacedock" : 1},
    "Sardakk"  	: {"carrier" : 2, "cruiser" : 1, "infantry" : 5, "spacedock" : 1, "pds" : 1},
    "Sol" 	 	: {"carrier" : 2, "destroyer" : 1, "fighter" : 3, "infantry" : 5, "spacedock" : 1},
    "Titans"  	: {"dreadnought" : 1, "cruiser" : 2, "fighter" : 2, "infantry" : 3, "spacedock" : 1},
    "Winnu"  	: {"carrier" : 1, "cruiser" : 1, "fighter" : 2, "infantry" : 2, "spacedock" : 1, "pds" : 1},
    "Xxcha"  	: {"carrier" : 1, "cruiser" : 2, "fighter" : 3, "infantry" : 4, "spacedock" : 1, "pds" : 1},
    "Yin" 		: {"carrier" : 2, "destroyer" : 1, "fighter" : 4, "infantry" : 4, "spacedock" : 1},
    "Yssaril" 	: {"carrier" : 2, "cruiser" : 1, "fighter" : 2, "infantry" : 5, "spacedock" : 1, "pds" : 1},
}

spaceUnits = ["cruiser", "destroyer", "fighter", "flagship", "warsun", "dreadnought", "carrier"]
groundUnits = ["spacedock", "pds", "infantry", "mech"]

emptyFleet = {
	"list" :{
		"spacedock" 	: 0, 
		"pds" 			: 0, 
		"infantry" 		: 0, 
		"cruiser" 		: 0, 
		"destroyer" 	: 0, 
		"fighter" 		: 0, 
		"flagship" 		: 0, 
		"warsun" 		: 0, 
		"dreadnought" 	: 0, 
		"carrier" 		: 0, 
		"mech" 			: 0,
		},
	"color" : ""
}

emptyGroundFleet = {
	"list" :{
		"spacedock" 	: 0, 
		"pds" 			: 0, 
		"infantry" 		: 0, 
		"mech" 			: 0,
		},
	"color" : ""
}

##Coords for drawing on the tiles, Draw order is: Tile, Space Tokens, Player Tokens, Attachments, Planet Units/OwnerLabel, Space Units, Labels (planet then space)
systemOverlayLookup = {
	0 : {
		"sptoken" : [[-66,-66], [102, 0], [0, 102], [-102, 0], [-28, 66], [94,-94], [94, 94], [-94,94]],
		"pltoken" : [[60,-53],[11,-4]],
		"planets"  : {
			"basecoords" : [[0,0]],
			"attachments" : [[25, 40],[-25, 25]],
			"gdunit" : {
				"spacedock" : {"unit" : [-40,-38], "label" : [-41,-65]},
				"pds"		: {"unit" : [-13,-37], "label" : [-14,-65]},
				"infantry"	: {"unit" : [ 14,-37], "label" : [ 13,-65]},
				"mech"		: {"unit" : [ 44,-41], "label" : [ 40,-65]},
				"pllabel" 	: {"unit" : [  0, 15]},
			},
		},
		"spunit"  : {
			"carrier"		: {"unit" : [-66,-95], 	"label" : [-43,-110]},
			"cruiser"		: {"unit" : [-58, 89], 	"label" : [-35, 70 ]},
			"destroyer"		: {"unit" : [-9 , 101], "label" : [-8 , 70 ]},
			"dreadnought"	: {"unit" : [-99,-2], 	"label" : [-72, -2 ]},
			"fighter"		: {"unit" : [-13,-108], "label" : [ 11,-110]},
			"flagship"		: {"unit" : [27, 89],	"label" : [ 27, 52 ]},
			"infantry"		: {"unit" : [-99,-40],	"label" : [-72,-37 ]},
			"mech"			: {"unit" : [66, 101],	"label" : [ 63, 76 ]},
			"warsun"		: {"unit" : [46,-101],	"label" : [ 80,-86 ]},
			"pllabel" 		: {"unit" : [  0 , 0  ], "offset": [ 5,-5  ]},
		},
	},
	1 : {
		"sptoken" : [[-83,44], [-58, 69], [33, 94]],
		"pltoken" : [[60,-53],[11,-4]],
		"planets"  : {
			"basecoords" : [[0,0]],
			"attachments" : [[40, 40],[-25, 25]],
			"gdunit" : {
				"spacedock" : {"unit" : [-40,-38], "label" : [-41,-65]},
				"pds"		: {"unit" : [-13,-37], "label" : [-14,-65]},
				"infantry"	: {"unit" : [ 14,-37], "label" : [ 13,-65]},
				"mech"		: {"unit" : [ 44,-41], "label" : [ 40,-65]},
				"pllabel" 	: {"unit" : [  0, 15]},
			},
		},
		"spunit"  : {
			"carrier"		: {"unit" : [-66,-95], 	"label" : [-43,-110]},
			"cruiser"		: {"unit" : [-58, 89], 	"label" : [-35, 70 ]},
			"destroyer"		: {"unit" : [-9 , 101], "label" : [-8 , 70 ]},
			"dreadnought"	: {"unit" : [-99,-2 ], 	"label" : [-72, -2 ]},
			"fighter"		: {"unit" : [-13,-108], "label" : [ 11,-110]},
			"flagship"		: {"unit" : [27, 89 ],	"label" : [ 27, 52 ]},
			"infantry"		: {"unit" : [-99,-40],	"label" : [-72,-37 ]},
			"mech"			: {"unit" : [66, 101],	"label" : [ 63, 76 ]},
			"warsun"		: {"unit" : [46,-101],	"label" : [ 80,-86 ]},
			"pllabel" 		: {"unit" : [  0 , 0  ], "offset": [ 5 ,-5 ]},
		},
	},
	2 : {
		"sptoken" : [[-83,44], [-58, 69], [33, 94]],
		"pltoken" : [[82,-65],[11,-4]],
		"planets"  : {
			"basecoords" : [[-59, -21], [59, 21]],
			"attachments" : [[60, 32],[-25, 25]],
			"gdunit" : {
				"spacedock" : {"unit" : [-40,-38], "label" : [-41,-65]},
				"pds"		: {"unit" : [-13,-37], "label" : [-14,-65]},
				"infantry"	: {"unit" : [ 14,-37], "label" : [ 13,-65]},
				"mech"		: {"unit" : [ 44,-41], "label" : [ 40,-65]},
				"pllabel" 	: {"unit" : [  0, 15]},
			},
		},
		"spunit"  : {
			"carrier"		: {"unit" : [-112,-2  ], "label" : [-136, 0]},
			"cruiser"		: {"unit" : [-35 , 95 ], "label" : [-35, 57]},
			"destroyer"		: {"unit" : [-8  , 107], "label" : [ 18,116]},
			"dreadnought"	: {"unit" : [-50 ,-4  ], "label" : [-50, 31]},
			"fighter"		: {"unit" : [50  ,-109], "label" : [74,-107]},
			"flagship"		: {"unit" : [-63 , 96 ], "label" : [-63, 57]},
			"infantry"		: {"unit" : [-107,-41 ], "label" : [-83,-45]},
			"mech"			: {"unit" : [-83 , 5  ], "label" : [-83,-20]},
			"warsun"		: {"unit" : [103 ,-8  ], "label" : [103,-41]},
			"pllabel" 		: {"unit" : [  0 , 0  ], "offset": [ 5 ,-5 ]},
		},
	},
	3 : {
		"sptoken" : [[-90,5], [-58, 69], [33, 94]],
		"pltoken" : [[68,-60],[11,-4]],
		"planets"  : {
			"basecoords" : [[-59, -46], [68, -36], [-24,67]],
			"attachments" : [[40, 40],[-25, 25]],
			"gdunit" : {
				"spacedock" : {"unit" : [-40,-38], "label" : [-41,-65]},
				"pds"		: {"unit" : [-13,-37], "label" : [-14,-65]},
				"infantry"	: {"unit" : [ 14,-37], "label" : [ 13,-65]},
				"mech"		: {"unit" : [ 44,-41], "label" : [ 40,-65]},
				"pllabel" 	: {"unit" : [  0, 5]},
			},
		},
		"spunit"  : {
			"carrier"		: {"unit" : [-99 ,-35 ],	"label" : [-123	,-20 ]	},
			"cruiser"		: {"unit" : [-65 , 96 ],	"label" : [-90	, 76 ]	},
			"destroyer"		: {"unit" : [ 32 , 109],	"label" : [ 5 	, 100]	},
			"dreadnought"	: {"unit" : [-99 , 36 ],	"label" : [-127	, 19 ]	},
			"fighter"		: {"unit" : [ 34 ,-118],	"label" : [ 58	,-120]	},
			"flagship"		: {"unit" : [ 32 , 109],	"label" : [ 60	, 89 ]	},
			"infantry"		: {"unit" : [ 58 ,-98 ],	"label" : [ 82	,-98 ]	},
			"mech"			: {"unit" : [ 83 , 49 ],	"label" : [ 112 , 42 ]	},
			"warsun"		: {"unit" : [-30 , 102],	"label" : [ 4 	, 117]	},
			"pllabel" 		: {"unit" : [  0 , 0  ],	"offset": [ 5   ,-5  ]  },
		},
	},
}

## Offest for the ground forces on a big planet (Hope's End, Primor, Mecatol, Elysium)
bigPlanetOffset = [0, -14]

## Mirage has a unique position for each tiletype as it cannot be placed in the normal spot
getMiragePos = {
	0 : [-83,44],
	1 : [-83,44],
	2 : [-83,44],
	3 : [-90,5],
}

## Token Lookup
spaceToken = {
	0 : {"name" : "Creuss Alpha Token", "image" : "alphaTokenGhosts", 	"wormhole" : "alpha"},
	1 : {"name" : "Creuss Beta Token" , "image" : "betaTokenGhosts" , 	"wormhole" : "beta"},
	2 : {"name" : "Creuss Gamma Token", "image" : "gammaTokenGhosts", 	"wormhole" : "gamma"},
	3 : {"name" : "Ion Alpha Token", 	"image" : "alphaIonToken", 		"wormhole" : "alpha"},
	4 : {"name" : "Ion Beta Token",		"image" : "betaIonToken", 		"wormhole" : "beta"},
	5 : {"name" : "Gamma Token",		"image" : "gammaToken", 		"wormhole" : "gamma"},
	6 : {"name" : "Frontier Token",		"image" : "frontier", 			"wormhole" : "none"},
	10: {"name" : "Mirage",				"image" : "mirage", 			"wormhole" : "none"},
}

attachments = {
	0 : {"name" : "Propulsion Research Facility", 	"tokens" : [{"image" : "blueSkipToken", "value" : 0}]},
	1 : {"name" : "Cybernetic Research Facility", 	"tokens" : [{"image" : "yellowSkipToken", "value" : 0}]},
	2 : {"name" : "Biotic Research Facility", 		"tokens" : [{"image" : "greenSkipToken", "value" : 0}]},
	3 : {"name" : "Propulsion Research Facility (R/I)", "tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},
	4 : {"name" : "Cybernetic Research Facility (R/I)", "tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},
	5 : {"name" : "Warfare Research Facility (R/I)", 	"tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},
	6 : {"name" : "Biotic Research Facility (R/I)", 	"tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},

	7 : {"name" : "Warfare Research Facility", 		"tokens" : [{"image" : "redSkipToken", "value" : 0}]},
	8 : {"name" : "Warfare Research Facility (R/I)", 	"tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},
	9 : {"name" : "Lazax Survivors",	"tokens" : [{"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 2}]},
	10: {"name" : "Mining World", 		"tokens" : [{"image" : "ResToken", "value" : 2}]},
	11: {"name" : "Rich World", 		"tokens" : [{"image" : "ResToken", "value" : 1}]},

	12: {"name" : "Dyson Sphere", 		"tokens" : [{"image" : "ResToken", "value" : 2}, {"image" : "InfToken", "value" : 1}]},
	13: {"name" : "Paradise World", 	"tokens" : [{"image" : "InfToken", "value" : 2}]},
	14: {"name" : "Tomb of Emphidia", 	"tokens" : [{"image" : "crownToken", "value" : 0}, {"image" : "InfToken", "value" : 1}]},
	15: {"name" : "Demilitarized Zone", "tokens" : [{"image" : "DMZToken", "value" : 0}]},

	16: {"name" : "Nano-Forge", 		"tokens" : [{"image" : "LegendaryToken", "value" : 0}, {"image" : "ResToken", "value" : 2}, {"image" : "InfToken", "value" : 2}]},
	17: {"name" : "Stellar Converter", 	"tokens" : [{"image" : "destroyedPlanetToken", "value" : 0}]},

	18: {"name" : "Sleeper Titan", 		"tokens" : [{"image" : "SleeperToken", "value" : 0}]},
	19: {"name" : "Terraform", 			"tokens" : [{"image" : "TraitsToken", "value" : 0}, {"image" : "ResToken", "value" : 1}, {"image" : "InfToken", "value" : 1}]},
	20: {"name" : "Geoform", 			"tokens" : [{"image" : "PDSToken", "value" : 0}, {"image" : "ResToken", "value" : 3}, {"image" : "InfToken", "value" : 3}]},

	21: {"name" : "Dimensional Tear", 	"tokens" : [{"image" : "GRToken", "value" : 0}]},
}

## Tokens which aren't placed in their standard token locations
tokenExceptions = {
	"mirage"  : "planet",
	"dimtear" : "spacedock",
	"sleeper" : "pds",
	"DMZ"	  : "cover",
	"destroyed" : "cover",
}
